@startuml

enum Role {
    USER,
    ADMIN
}

class TaskEntity {
    + id: Long
    + title: String
    + description: String
    + dueDate: Instant
    + isDone: Boolean
    + taskListEntity: TaskListEntity
    + createdBy: UserEntity
}

class TaskListEntity {
    + id: Long
    + name: String
    + tasks: List<TaskEntity>
    + createdBy: UserEntity
    {method} + addTaskToTaskList(taskEntity: TaskEntity): void
    {method} + updateTaskToTaskList(task: TaskEntity): void
}

class UserEntity {
    + id: Long
    + username: String
    + password: String
    + email: String
    + role: Role
    + createdTasks: List<TaskEntity>
    + createdTaskLists: List<TaskListEntity>
}

TaskEntity -> TaskListEntity : taskListEntity
TaskEntity -> UserEntity : createdBy
TaskListEntity --> UserEntity : createdBy

@enduml